// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT5XkFAfnkYWVO0is8-Ys23LuU0kPF-jc',
    appId: '1:445642624334:web:855c4388cd887ed798e21f',
    messagingSenderId: '445642624334',
    projectId: 'flutter-app-mynotes',
    authDomain: 'flutter-app-mynotes.firebaseapp.com',
    storageBucket: 'flutter-app-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZwoaV4nL8SF2M34WxS1yU1fNYRsAq-0',
    appId: '1:445642624334:android:474ed003f5dfe29f98e21f',
    messagingSenderId: '445642624334',
    projectId: 'flutter-app-mynotes',
    storageBucket: 'flutter-app-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8aqLWrTcQ1uRiqdZarbuF-evTuVoUsFs',
    appId: '1:445642624334:ios:5495e645100b11a998e21f',
    messagingSenderId: '445642624334',
    projectId: 'flutter-app-mynotes',
    storageBucket: 'flutter-app-mynotes.appspot.com',
    iosClientId: '445642624334-tcg7hari6bi7hr55k9745f9r50shmnn6.apps.googleusercontent.com',
    iosBundleId: 'com.teednet.mynotes',
  );
}
